openapi: 3.0.1
info:
  title: Account Service
  description: The account service helps to create and manage product accounts serviced by the financial institutions. It is also used to retrieve information about the existing accounts and maintain information of new accounts.
  version: 11.0.0_FIN-Inq_Deposit
paths:
  /acctservice/acctmgmt/accounts/secured:
    post:
      tags:
        - Get Accounts
      summary: Get Accounts.
      description: "Retrieves account-related information of the existing Checking, Savings, CD or Loan account records.<br>\n        For more information about the Accounts domain, <a href=\"../docs/?path=docs/fintechs/accounts.md\" title=\"Click to open\">click here.</a><br><br>\n        <b>Relates to:</b>\n          <ul> \n            <li><a href=\"../docs/?path=docs/banks-and-CU/deposits.md\" title=\"Click to open\">Deposits</a></li>\n            <li><a href=\"../docs/?path=docs/banks-and-CU/loans.md\" title=\"Click to open\">Loans</a></li>\n            <li><a href=\"../docs/?path=docs/banks-and-CU/bank-servicing.md\" title=\"Click to open\">Bank Servicing</a></li>\n            <li><a href=\"../docs/?path=docs/banks-and-CU/cash-mgt.md\" title=\"Click to open\">Cash Management</a></li>\n            <li><a href=\"../docs/?path=docs/banks-and-CU/treasury-services.md\" title=\"Click to open\">Treasury Services</a></li>\n            <li><a href=\"../docs/?path=docs/banks-and-CU/riskMgt.md\" title=\"Click to open\">Risk and Performance Management</a></li>\n          </ul>"
      operationId: getAccountsSecured
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getAccountsSecuredRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAccountsSecuredResponse'
        default:
          description: 'To view the complete list of response codes, <a href="../docs/?path=docs/response-codes.md" title="Click to open">click here.</a>'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAccountsSecuredResponse'
      x-group-name: Account Service
      x-proxy-name: Get Account Details
      x-child-product-name: Accounts
      x-core: Finxact-Deposit
    parameters:
      - $ref: https://swaggerhub.onefiserv.net/v1/domains/Bank_Sol_Org/ESF_Reusable-content/11.0.0#/components/parameters/EFXHeader
components:
  schemas:
    getAccountsSecuredRequest:
      required:
        - AcctSel
      properties:
        AcctSel:
          required:
            - AcctKeys
          type: object
          properties:
            AcctKeys:
              required:
                - AcctId
              type: object
              properties:
                AcctId:
                  maxLength: 36
                  type: string
                  description: Unique identification number of an account record.
                AcctType:
                  enum:
                    - DDA
                    - MMA
                    - SDA
                    - CDA
                    - CMA
                  type: string
                  description: "Type of an account.\n\n\n\nFor more information about account types, refer to the Account Types section in <a href=\"../docs?path=docs/api-glossary.md\" target=\"_blank\" title=\"Click to open in a new tab\"> Glossary</a>.\n\n**Note:** Some of the valid values for this field are:\n\n- DDA: Demand Deposit Account\n\n- MMA:  Money Market Account\n\n- SDA: Savings Deposit Account\n\n- CDA: Certificate of Deposit Account\n\n- CMA: Cash Management Account\n\n"
              description: Unique information to identify the account record.
          description: Details of the selection criteria used for account inquiry.
    getAccountsSecuredResponse:
      required:
        - AcctRec
      properties:
        Status:
          $ref: https://swaggerhub.onefiserv.net/v1/domains/Bank_Sol_Org/ESF_Reusable-content/11.0.0#/components/schemas/StatusType
        AcctRec:
          required:
            - AcctKeys
            - AcctStatus
          type: object
          properties:
            AcctKeys:
              required:
                - AcctId
              type: object
              properties:
                AcctId:
                  maxLength: 36
                  type: string
                  description: Unique identification number of an account record.
                AcctType:
                  enum:
                    - DDA
                    - MMA
                    - SDA
                    - CDA
                    - CMA
                  type: string
                  description: "Type of an account.\n\n\n\nFor more information about account types, refer to the Account Types section in <a href=\"../docs?path=docs/api-glossary.md\" target=\"_blank\" title=\"Click to open in a new tab\"> Glossary</a>.\n\n**Note:** Some of the valid values for this field are:\n\n- DDA: Demand Deposit Account\n\n- MMA:  Money Market Account\n\n- SDA: Savings Deposit Account\n\n- CDA: Certificate of Deposit Account\n\n- CMA: Cash Management Account\n\n"
              description: Unique information to identify the account record.
            DepositAcctInfo:
              type: object
              properties:
                AcctDtlStatus:
                  enum:
                    - Active
                    - Closed
                    - Dormant
                    - Escheated
                    - Inactive
                  type: string
                  description: "Current status of an account.\n\n\n\n"
                CurCode:
                  required:
                    - CurCodeValue
                  type: object
                  properties:
                    CurCodeType:
                      enum:
                        - ISO4217-Alpha
                      type: string
                      description: "Standard ISO currency code format. \n\nRefer to the <a href=\"https://en.wikipedia.org/wiki/ISO_4217\" target=\"_blank\" title=\"Click to open in a new tab\">ISO 4217 codes </a> to view the list of all currency codes."
                    CurCodeValue:
                      type: string
                      description: "Currency code value as per the ISO4217-Alpha format.\n\n\n\nPresently only USD currency code is supported."
                  description: "Details of currency code.\n\n"
                AcctPref:
                  type: object
                  properties:
                    CurCode:
                      required:
                        - CurCodeValue
                      type: object
                      properties:
                        CurCodeType:
                          enum:
                            - ISO4217-Alpha
                          type: string
                          description: "Standard ISO currency code format. \n\nRefer to the <a href=\"https://en.wikipedia.org/wiki/ISO_4217\" target=\"_blank\" title=\"Click to open in a new tab\">ISO 4217 codes </a> to view the list of all currency codes."
                        CurCodeValue:
                          type: string
                          description: "Currency code value as per the ISO currency code format set in the CurCodeType field.\n\nFor example, currency code for the US dollar in alpha and numeric formats are:\n\n- USD (in ISO4217-Alpha format) \n\n- 840 (in ISO4217-Numeric format)\n\nPresently only USD currency code is supported.\n\n\n\n**Note:** Refers to reporting currency of the account."
                      description: Details of currency code.
                  description: Details to specify account preferences.
                AcctIdent:
                  type: array
                  items:
                    properties:
                      AcctIdentType:
                        enum:
                          - PORT
                        type: string
                        description: Type of account identifiers.
                      AcctIdentValue:
                        maxLength: 36
                        type: string
                        description: Account identification value.
                  description: Details of the unique identifier of an account record used as alternative identifier.
                ProductIdent:
                  maxLength: 42
                  type: string
                  description: Unique identifier of a product. This value is used to indicate the processing options of the account.
                Desc:
                  maxLength: 200
                  type: string
                  description: Description of the product used to set up the account.
                InitialAmount:
                  type: object
                  properties:
                    Amt:
                      type: number
                      description: Amount in decimal format.
                  description: Details of the certificate value of a time deposit account.
                OpenDt:
                  type: string
                  description: "Date on which the account record is created.\n\n\n\nFormat: yyyy-mm-dd \n\nExample: 2021-11-20"
                  format: date
                ClosedDt:
                  type: string
                  description: "Date on which the account is closed.\n\n\n\nFormat: yyyy-mm-dd \n\nExample: 2021-11-20"
                  format: date
                Term:
                  required:
                    - TermUnits
                  type: object
                  properties:
                    Count:
                      type: integer
                      description: Number of term units for which a term deposit is effective.
                      format: int64
                    TermUnits:
                      enum:
                        - Days
                        - Months
                        - Years
                      type: string
                      description: "Units to define the term of the account. \n\n\n\n"
                  description: Term details for a deposit account.
                MaturityDt:
                  type: string
                  description: "Date of maturity of a loan account.\n\n\n\nFormat: yyyy-mm-dd \n\nExample: 2021-11-20"
                  format: date
                Nickname:
                  maxLength: 80
                  type: string
                  description: Name that customer can assign to the account for easy identification.
                AcctTitle:
                  maxLength: 255
                  type: string
                  description: "Title of account. This value is typically used to indicate the ownership or responsibility of account holder and manner in which the ownership or responsibility is assigned. \n\nFor example, John Doe CUSTODIAN."
                ClassCode:
                  type: string
                  description: Code to group accounts for the purpose of processing and reporting.
                AcctStmtData:
                  type: object
                  properties:
                    StmtTimeFrame:
                      type: array
                      items:
                        properties:
                          RecurType:
                            enum:
                              - Yearly
                              - Monthly
                              - Daily
                              - BusinessDaily
                            type: string
                            description: 'Recurrence type indicates the pattern of recurrence. '
                          RecurInterval:
                            type: integer
                            description: "Recurrence interval between two successive occurrences of statement generation.\n\nFor example, if the recurrence type value is set to 'Monthly' and the recurrence interval set to '1', then there will be 1-month interval between the next statement.\n\nThe default value is set to 1.\n\n"
                            format: int64
                          DayOfMonth:
                            type: string
                            description: Numeric value representing the day of the month of occurrence.
                          WeekendOption:
                            enum:
                              - NextBusinessDay
                              - LastBusinessDay
                              - ActualDate
                            type: string
                            description: "Option that indicate the functionality for weekends.\n\nFor example, tranfers are processed on weekends."
                      description: Time frame details for the account statement.
                    NextStmtDt:
                      type: string
                      description: "Date on which the next statement is generated.\n\n\n\nFormat: yyyy-mm-dd \n\nExample: 2021-11-20"
                      format: date
                    LastStmtDt:
                      type: string
                      description: "Date on which last statement was generated.\n\n\n\nFormat: yyyy-mm-dd \n\nExample: 2021-11-20"
                      format: date
                  description: Details of the account statement processing data.
                Rate:
                  type: number
                  description: Current interest rate for the account.
                IntRateData:
                  type: object
                  properties:
                    AccrualMethod:
                      enum:
                        - Daily
                        - Simple
                      type: string
                      description: Method of interest accrual.
                  description: Details of the interest rate processing for the account.
                AcctBal:
                  type: array
                  items:
                    required:
                      - BalType
                      - CurAmt
                    properties:
                      BalType:
                        enum:
                          - InterestAccrued
                          - Ledger
                          - Current
                          - Avail
                          - Sweep
                          - AvailCredit
                          - Hold
                          - CreditLimit
                          - BalanceLastStatement
                          - CustCollected
                        type: string
                        description: "Type of account balance.\n\n"
                      CurAmt:
                        type: object
                        properties:
                          Amt:
                            type: number
                            description: Amount in decimal format.
                          CurCode:
                            required:
                              - CurCodeValue
                            type: object
                            properties:
                              CurCodeType:
                                enum:
                                  - ISO4217-Alpha
                                type: string
                                description: "Standard ISO currency code format. \n\nRefer to the <a href=\"https://en.wikipedia.org/wiki/ISO_4217\" target=\"_blank\" title=\"Click to open in a new tab\">ISO 4217 codes </a> to view the list of all currency codes."
                              CurCodeValue:
                                type: string
                                description: "Currency code value as per the ISO currency code format set in the CurCodeType field.\n\nFor example, currency code for the US dollar in alpha and numeric formats are:\n\n- USD (in ISO4217-Alpha format) \n\n- 840 (in ISO4217-Numeric format)\n\nPresently only USD currency code is supported.\n\n"
                            description: Details of currency code.
                        description: Details of the currency amount.
                  description: Amount of balance present in a financial institution account.
                AcctPeriodData:
                  type: array
                  items:
                    required:
                      - AcctAmtType
                    properties:
                      AcctAmtType:
                        enum:
                          - IntPaid
                          - Deposit
                          - Statement
                        type: string
                        description: Type of amount in account.
                      AcctPeriodType:
                        enum:
                          - YTD
                          - PriorYr
                          - LTD
                          - CTD
                          - PriorCycle
                        type: string
                        description: Type of the account period.
                      Amt:
                        type: number
                        description: Amount in decimal format.
                      Rate:
                        type: number
                        description: Current interest rate for the account.
                      LastOccuranceDt:
                        pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?'
                        type: string
                        description: "Date of the last occurrence.\n\n\n\nFormat: yyyy-MM-ddTHH:mm:ss.SSS\n\nExample: 2021-01-31T23:59:59.999"
                  description: 'Accounting period data details such as last interest payment, nonsufficient funds, overdraft activity year to date, current month, and cycle to date.'
                TrnRestriction:
                  type: string
                  description: Client defined restrictions for transactions applied to the account during the transaction posting.
                DocDistributionOption:
                  type: string
                  description: "Client defined method to indicate the document distribution method used for processing the notices and statement forms.\n\n"
                IntDispData:
                  type: object
                  properties:
                    NextIntPmtDt:
                      type: string
                      description: "Date of next interest payment for the account.\n\n\n\nFormat: yyyy-mm-dd \n\nExample: 2021-11-20"
                      format: date
                  description: Details of the interest disposition for the account.
              description: Details of the deposit account.
            AcctStatus:
              required:
                - AcctStatusCode
              type: object
              properties:
                AcctStatusCode:
                  enum:
                    - Valid
                  type: string
                  description: Status code of an account.
                EffDt:
                  pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{3})?((-|\+)[0-9]{2}:[0-9]{2})?)?)?'
                  type: string
                  description: "Effective date and time when the account status is changed. \n\n\n\nFormat: yyyy-MM-ddTHH:mm:ss.sss\n\nExample: 2021-01-31T23:59:59.999"
              description: Status details of the account.
          description: Details of an account record.