openapi: 3.0.0
info:
  version: "1.0.0"
  contact: 
    name: andy bahmueller
    email: andy.bahmueller@fiserv.com
  title: 'DocumentPreferences'
  description: 'Data that describes document production preferences'
paths:
  /document-preferences/v1/:
    parameters:
      - name: Fiserv-OrganizationId
        in: header
        required: true
        schema:
          type: string
        description: >-
            Organization Identifier is a unique ID that represents the financial institution 
            or holding vendor.  This ID does not necessarily match the Org ID or Bank ID in 
            the backend system.  To ensure uniqueness across all institutions in all parts 
            of the world, use the Dun and Bradstreet number.
      - name: Fiserv-TransactionId
        in: header
        required: true
        schema:
          type: string
        description: >-
            Transaction Identifier. This is the transaction UUID of the current message.
      - name: Fiserv-ClientApplicationName
        in: header
        required: true
        schema: 
          type: string
        description: >-
            Name of the application making the service request (e.g. Architect, 
            Commercial Center, etc.).
      - name: Fiserv-Channel
        in: header
        required: true
        schema:
          type: string
        description: >-
            Indicates the channel used by the client application.
      - name: Fiserv-ClientDateTime
        in: header
        required: true
        schema:
          type: string
        description: >-
            Client date and time as reported by the client application that is 
            making the service request.
      - name: Fiserv-VendorId
        in: header
        required: true
        schema:
          type: string
        description: >-
            An identifier, supplied by Fiserv, that represents the vendor using 
            this API service.
    post:
      summary: "Adds a document preference for an existing customer/owner."
      tags:
        - Add Document Preference
      x-group-name: Document Preferences Service
      x-proxy-name: Add Document Preference
      x-child-product-name: ["Leve","Accounts and Transactions"]
      operationId: DocumentPreferenceAddOperator
      description: "This service adds a document preference."
      requestBody:
        description: DocumentPreferences
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/AccountRefRequest'
                - $ref: '#/components/schemas/CardRefRequest'
      responses: 
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentPreferenceResponse'
        default: 
          description: "Unexpected error"
          content:
            application/json:
              schema: 
                 $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    AccountRefRequest:
      title: AccountRefRequest
      type: object
      properties:
        id:
          type: string
          description: >-
              Generic identifier that contains no sensitive data and should be 
              utilized as the key within URI when performing RESTful operations
        number:
          type: string
          description: >-
              Actual account number as defined by the bank or credit union
        type:
          type: string
          description: >-
              Classifies the type of product with which an account is associated 
              at a high level; Deposit, Loan, Card.  Additional detail about the 
              account is at the account object level
          enum:
            - Deposit
            - Loan
        detailType:
          type: string
          description: >- 
              Detailed account type
          enum:
            - Brokerage
            - CertificateOfDeposit
            - Checking
            - Club
            - Commercial
            - Construction
            - Consumer
            - DebitCard
            - Escrow
            - FlexibleSpending
            - HealthSavings
            - Installment
            - LineOfCredit
            - MoneyMarket
            - Mortgage
            - Passbook
            - Personal
            - Retirement
            - Savings
            - ShareDraft
            - Student        
        PartyRef:
          $ref: '#/components/schemas/PartyRef'
        DocumentPreferenceAdd:
          $ref: '#/components/schemas/DocumentPreferenceAdd'
    CardRefRequest:
      title: CardRefRequest
      type: object
      properties:
        id:
          type: string
          description: >-
              Generic identifier that contains no sensitive data and should be 
              utilized as the key within URI when performing RESTful operations
        number:
          type: string
          description: >-
              Full card number as it appears on the card
        type:
          type: string
          description: >-
              The type of card being described
          enum:
            - ATM
            - Credit
            - Debit
            - PrePaid
            - Rewards
            - Virtual
        PartyRef:
          $ref: '#/components/schemas/PartyRef'
        DocumentPreferenceAdd:
          $ref: '#/components/schemas/DocumentPreferenceAdd'
    DocumentPreferenceAdd:
      title: DocumentPreferenceAdd
      type: object
      properties:
        type:
          type: string
          description: >-
              Type of document preference being supplied
          enum: 
            - Account
            - Card
            - Customer
        document:
          type: array
          description: >-
              Document list to set preferences for
          items:
            type: string
        documentGroup:
          type: string
          description: >-
              Document group to set preferences for
        isDigital:
          type: boolean
          description: >-
              Should the document to be produced digitally (true)
        isPrinted:
          type: boolean
          description: >-
              Should the document be printed (true)
        notifications:
          type: array
          description: >-
              List of notifications associated document preference
          items:
            $ref: '#/components/schemas/Notification'

    Notification:
      title: Notification
      type: object
      required:
        - emailAddress
      properties:
        type:
          type: string
          description: >-
              Type of notification being described
          enum:
            - Both
            - Email
            - Phone
        emailAddress:
          type: string
          description: >-
              Email address used for notification
        phone:
          $ref: '#/components/schemas/Phone'
    PartyRef:
      title: PartyRef
      type: object
      properties:
        id:
          type: string
          description: >-
              Id value maintained by the core representing the party
        number:
          type: string
          description: >-
              Actual number of the party
        DocumentPreferenceAdd:
          $ref: '#/components/schemas/DocumentPreferenceAdd'
    Phone:
      title: Phone
      type: object
      properties:
        countryCode:
          type: string
          description: >-
              Country code of phone number.  Numeric values only
        number:
          type: string
          description: >-
              Phone number being returned.  Numeric values only
    DocumentPreferenceResponse:
      title: DocumentPreferenceResponse
      type: object
      properties:
        messages: 
          type: array
          description: >-
              More than one error, warning or informational messages may be
              returned in the response.
          items:
            $ref: '#/components/schemas/Message'
        links:
          $ref: '#/components/schemas/Links'
    ErrorMessage:
      title: ErrorMessage
      type: object
      properties:
        messages: 
          type: array
          description: >-
              More than one error, warning or informational messages may be
              returned in the response.
          items:
            $ref: '#/components/schemas/Message'
        links:
          $ref: '#/components/schemas/Links'
    Links:
      title: Links
      required:
        - self
      type: object
      properties:
        self: 
          type: string
          format: uri
        first: 
          type: string
          format: uri 
        previous: 
          type: string
          format: uri
        next: 
          type: string
          format: uri
        last: 
          type: string
          format: uri
    Message:
      title: Message
      required:
        - type
        - title
      type: object
      properties:
        type:
          type: string
          description: >-
              A URI reference [RFC3986] that identifies the problem type.
        title:
          type: string 
          description: >-
              A short human-readable summary of the problem type.
        detail:
          type: string
          description: >-
              A human-readable description of the specific error  
        instance:
          type: string
          description: >-
              This optional key may be present, with a unique URI for the 
              specific error; this will often point to an error log for that 
              specific response.