################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

header:
  productDescription: To onboard properly into the Developer Studio as a new tenant each product must support these APIs so that we can retrieve product specific API specifications and documentation.
getStarted: /docs/getting-started.md
benefits:
  - title: Transform Customer Experiences
    description: Pre-certified integrations to value added solutions and third-party providers that power next-generation commerce experiences.
  - title: Accelerate Revenue
    description: Intelligent orchestration layer that reduces code complexity and operational costs.
  - title: Optimize Commerce
    description: Backoffice automation with a modern set of tools and APIs.
guides:
  - title: Setup a tenant
    description: Fiserv Products within the Fiserv portfolio that are showcased through the studio are known as tenants. Tenants standup a tenant server that will serve all the content through the studio for developers visiting the Fiserv Developer Studio.
    link: docs/getting-started/setup-tenant/setup-tenant.md
  - title: Preview and Publish
    description: This quick start guide will provide you with the necessary steps to get you from API Specification to ready-to-preview/publish API Documentation in 10 minutes flat.
    link: docs/getting-started/preview-and-publish-content/preview-and-publish.md
  - title: Using Markdown
    description: Markdown is a lightweight markup language that you can use to add formatting elements to plaintext text documents.
    link: docs/resources/markdown-support.md
featuredFeatures:
  - title: Documentation 1
    groupName: Guides
    featured: true
    description: Step by step documentation to setup and market your product.
    relatedDocs:
      - link: docs/getting-started/setup-tenant/setup-tenant.md
        title: Tenant setup
    relatedAPIs:
      - type: post
        path: /address
        title: Add Address
  - title: Documentation 1
    groupName: Howto
    featured: true
    description: Step by step documentation to setup and market your product.
    relatedDocs:
      - link: docs/getting-started/setup-tenant/setup-tenant.md
        title: Tenant setup
    relatedAPIs:
      - type: post
        path: /address
        title: Add Address
  - title: Documentation 2
    groupName: Guides
    description: Step by step documentation to setup and market your product.
    relatedDocs:
      - link: docs/getting-started/setup-tenant/setup-tenant.md
        title: Tenant setup
    relatedAPIs:
      - type: post
        path: /address
        title: Add Address
  - title: Documentation 3
    groupName: Guides
    description: Step by step documentation to setup and market your product.
    relatedDocs:
      - link: docs/getting-started/setup-tenant/setup-tenant.md
        title: Tenant setup
    relatedAPIs:
      - type: post
        path: /address
        title: Add Address
  - title: Documentation 2
    groupName: Howto
    description: Step by step documentation to setup and market your product.
    relatedDocs:
      - link: docs/getting-started/setup-tenant/setup-tenant.md
        title: Tenant setup
    relatedAPIs:
      - type: post
        path: /address
        title: Add Address
  - title: Documentation 3
    groupName: Howto
    description: Step by step documentation to setup and market your product.
    relatedDocs:
      - link: docs/getting-started/setup-tenant/setup-tenant.md
        title: Tenant setup
    relatedAPIs:
      - type: post
        path: /address
        title: Add Address
