name: Sync all YAML files

on:
  push:
    paths:
      - 'reference/**/*.yaml'

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Sync all YAML files
      run: node sync-yaml-files.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
