name: Sync YAML Files

on:
  push:
    paths:
      - 'reference/**/*.yaml'

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Get previous commit
      id: prev-commit
      run: echo "PREV_COMMIT=$(git rev-parse HEAD^1)" >> $GITHUB_ENV

    - name: Debug previous commit
      run: echo "Previous commit: ${{ env.PREV_COMMIT }}"

    - name: Get changed file
      id: changes
      run: |
        git diff --name-only ${{ env.PREV_COMMIT }} HEAD
        CHANGED_FILE=$(git diff --name-only ${{ env.PREV_COMMIT }} HEAD | grep '.yaml' || true)
        echo "CHANGED_FILE=$CHANGED_FILE" >> $GITHUB_ENV

    - name: Debug changed file
      run: echo "Changed file: ${{ env.CHANGED_FILE }}"

    - name: Install dependencies
      run: npm install

    - name: Sync YAML files
      run: node sync-yaml-files.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
