---
openapi: 3.0.0
info:
  title: SafeDepositBoxes
  description: The Safe Deposit Boxes Service supports operations to add, update and retrieve safe deposit boxes serviced by financial institutions.
  contact:
    name: andy bahmueller
    email: andy.bahmueller@fiserv.com
  version: 1.0.0
servers:
- url: https://swaggerhub.onefiserv.net/virts/Bank_Sol_Org/safeDepositBoxesBSM/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://swaggerhub.onefiserv.net/virts/Bank_Sol_Org/SafeDepositBoxesBSM/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /safeDepositBoxes/v1/{safeDepositBoxId}:
    patch:
      tags:
      - Update Safe Deposit Box
      description: Updates a nickname associated with a safe deposit box
      operationId: updateSafeDepositBox
      parameters:
      - name: safeDepositBoxId
        in: path
        description: Generic value associated with the identifier associated with a single safe deposit box
        required: true
        style: simple
        explode: false
        schema:
          type: string
        examples:
          Sample:
            value: F17AA97E-4281-4E94-B045-BC0637D91C92
      - name: Fiserv-OrganizationId
        in: header
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Fiserv-OrganizationId'
      - name: Fiserv-TransactionId
        in: header
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Fiserv-TransactionId'
      - name: Fiserv-ClientApplicationName
        in: header
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Fiserv-ClientApplicationName'
      - name: Fiserv-Channel
        in: header
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Fiserv-Channel'
      - name: Fiserv-ClientDateTime
        in: header
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Fiserv-ClientDateTime'
      - name: Fiserv-VendorId
        in: header
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Fiserv-VendorId'
      requestBody:
        description: Update safe deposit box
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSafeDepositBoxRequest'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSafeDepositBoxResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-group-name: Safe Deposit Boxes Service
      x-proxy-name: Update Safe Deposit Box
      x-child-product-name:
      - Core Banking Limited
      - Accounts
components:
  schemas:
    Fiserv-OrganizationId:
      type: string
      description: Organization Identifier is a unique ID that represents the financial institution  or holding vendor.  This ID does not necessarily match the Org ID or Bank ID in  the backend system.  To ensure uniqueness across all institutions in all parts  of the world, use the Dun and Bradstreet number
    Fiserv-TransactionId:
      type: string
      description: Transaction Identifier. This is the transaction UUID of the current message
    Fiserv-ClientApplicationName:
      type: string
      description: Name of the application making the service request (e.g. Architect,  Commercial Center, etc.)
    Fiserv-Channel:
      type: string
      description: Indicates the channel used by the client application
    Fiserv-ClientDateTime:
      type: string
      description: Client date and time as reported by the client application that is  making the service request
    Fiserv-VendorId:
      type: string
      description: An identifier, supplied by Fiserv, that represents the vendor using this API service
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        messages:
          type: array
          description: More than one error, warning or informational messages may be returned in the response.
          items:
            $ref: '#/components/schemas/Message'
    Message:
      title: Message
      required:
      - title
      - type
      type: object
      properties:
        type:
          type: string
          description: A URI reference [RFC3986] that identifies the problem type
        title:
          type: string
          description: A short human-readable summary of the problem type
        detail:
          type: string
          description: 'A human-readable description of the specific error  '
        instance:
          type: string
          description: 'This optional key may be present, with a unique URI for the specific error;  this will often point to an error log for that specific response. '
    UpdateSafeDepositBoxRequest:
      title: UpdateSafeDepositBoxRequest
      type: object
      properties:
        nickname:
          type: string
          description: 'User defined name of the safe deposit box '
    UpdateSafeDepositBoxResponse:
      title: UpdateSafeDepositBoxResponse
      type: object
      properties:
        messages:
          type: array
          description: More than one error, warning or informational messages may be returned in the response.
          items:
            $ref: '#/components/schemas/Message'
